import './TechnicianApply.css'
import { useState } from 'react'

const specialties=['Diagnostics','Electrical','Brakes','Tires','Battery','A/C & Climate','Engine','Transmission','Sensors & Electronics','Programming / Coding','Detailing','Towing / Roadside','General Maintenance','Other']
const services=[['oil-change','Oil Change'],['transmission','Transmission'],['tyre-change','Tyre Change'],['flat-fix','Flat Fix'],['brake-service','Brake Service'],['air-conditioning','Air Conditioning'],['sensors','Sensors'],['programming','Programming'],['diagnostics','Diagnostics'],['battery','Battery'],['wash-detail','Wash & Detail'],['towing','Towing'],['other','Other']]
export default function TechnicianApply(){
 const [form,setForm]=useState({fullName:'',email:'',phone:'',dateOfBirth:'',address:'',city:'',state:'Georgia',zip:'',yearsExperience:'',certifications:'',toolsEquipment:'',serviceRadiusMiles:'50',availabilityNotes:'',insuranceInformation:'',references:'',licenseInformation:'',notes:'',mobileCapable:true,emergencyAvailable:false})
 const [selectedSpecialties,setSelectedSpecialties]=useState([]);const [selectedServices,setSelectedServices]=useState([]);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState('')
 const update=(key)=>(e)=>setForm(v=>({...v,[key]:e.target.value}))
 const toggle=(set,id)=>set(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
 async function submit(e){e.preventDefault();setError('');if(!selectedSpecialties.length)return setError('Select at least one specialty.');if(!selectedServices.length)return setError('Select at least one service you are qualified to perform.');setBusy(true);try{const url=import.meta.env.VITE_SUPABASE_URL,anon=import.meta.env.VITE_SUPABASE_ANON_KEY;const r=await fetch(`${url}/functions/v1/submit-technician-application`,{method:'POST',headers:{'Content-Type':'application/json',apikey:anon},body:JSON.stringify({...form,yearsExperience:form.yearsExperience?Number(form.yearsExperience):null,serviceRadiusMiles:form.serviceRadiusMiles?Number(form.serviceRadiusMiles):null,specialties:selectedSpecialties,services:selectedServices})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Could not submit application.');setDone(true)}catch(e){setError(e.message||'Could not submit application.')}finally{setBusy(false)}}
 if(done)return <main className="min-h-screen bg-paper px-5 pb-20 pt-32 text-ink"><div className="mx-auto max-w-3xl rounded-[2rem] border border-line bg-white p-8 md:p-12"><p className="text-xs font-semibold uppercase tracking-[.25em] text-blue">Viso technician network</p><h1 className="mt-4 text-5xl font-display tracking-[-.05em]">Application received.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">Thanks for your interest in working with Viso Mobile Autocare. We’ll review your experience, specialties, service capability and service area before approving your application.</p></div></main>
 return <main className="min-h-screen bg-paper px-5 pb-20 pt-28 text-ink"><div className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-blue">Work with Viso</p><h1 className="mt-3 max-w-4xl text-[clamp(3rem,7vw,6rem)] leading-[.9] tracking-[-.06em] font-display">Bring your skills to the road.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted">Viso is building a network of qualified mobile automotive professionals across Georgia. Tell us what you do, where you work and when you’re available.</p>
 <form onSubmit={submit} className="mt-10 grid gap-8 lg:grid-cols-[1.15fr_.85fr]">
  <section className="rounded-[2rem] border border-line bg-white p-6 md:p-8"><Section title="01 / ABOUT YOU"/><div className="grid gap-3 sm:grid-cols-2"><input className="field" placeholder="Full legal name *" value={form.fullName} onChange={update('fullName')} required/><input className="field" type="email" placeholder="Email *" value={form.email} onChange={update('email')} required/><input className="field" placeholder="Phone *" value={form.phone} onChange={update('phone')} required/><input className="field" type="date" value={form.dateOfBirth} onChange={update('dateOfBirth')}/><input className="field sm:col-span-2" placeholder="Street address" value={form.address} onChange={update('address')}/><input className="field" placeholder="City *" value={form.city} onChange={update('city')} required/><input className="field" placeholder="ZIP code *" value={form.zip} onChange={update('zip')} required/></div>
  <div className="mt-8 border-t border-line pt-7"><Section title="02 / YOUR SPECIALTY"/><p className="text-sm text-muted">Select every area you are qualified to work in. At least one is required.</p><div className="chips mt-4">{specialties.map(s=><button type="button" key={s} className={`chip ${selectedSpecialties.includes(s)?'selected':''}`} onClick={()=>toggle(setSelectedSpecialties,s)}>{s}</button>)}</div></div>
  <div className="mt-8 border-t border-line pt-7"><Section title="03 / SERVICES"/><p className="text-sm text-muted">These determine the jobs Viso can route to you.</p><div className="chips mt-4">{services.map(([id,label])=><button type="button" key={id} className={`chip ${selectedServices.includes(id)?'selected':''}`} onClick={()=>toggle(setSelectedServices,id)}>{label}</button>)}</div></div>
  <div className="mt-8 border-t border-line pt-7"><Section title="04 / EXPERIENCE & CAPABILITY"/><div className="grid gap-3 sm:grid-cols-2"><input className="field" placeholder="Years of experience" inputMode="numeric" value={form.yearsExperience} onChange={update('yearsExperience')}/><input className="field" placeholder="Service radius (miles)" inputMode="numeric" value={form.serviceRadiusMiles} onChange={update('serviceRadiusMiles')}/><textarea className="field sm:col-span-2" rows="3" placeholder="Certifications, training or qualifications" value={form.certifications} onChange={update('certifications')}/><textarea className="field sm:col-span-2" rows="3" placeholder="Tools, diagnostic equipment and mobile setup" value={form.toolsEquipment} onChange={update('toolsEquipment')}/><textarea className="field sm:col-span-2" rows="3" placeholder="Insurance information" value={form.insuranceInformation} onChange={update('insuranceInformation')}/><textarea className="field sm:col-span-2" rows="3" placeholder="License / credential information" value={form.licenseInformation} onChange={update('licenseInformation')}/></div></div>
  <div className="mt-8 border-t border-line pt-7"><Section title="05 / AVAILABILITY"/><div className="grid gap-3"><textarea className="field" rows="3" placeholder="Typical working days and hours" value={form.availabilityNotes} onChange={update('availabilityNotes')}/><textarea className="field" rows="3" placeholder="Professional references" value={form.references} onChange={update('references')}/><textarea className="field" rows="3" placeholder="Anything else Viso should know" value={form.notes} onChange={update('notes')}/></div><label className="mt-4 flex gap-3 text-sm text-muted"><input type="checkbox" checked={form.mobileCapable} onChange={e=>setForm(v=>({...v,mobileCapable:e.target.checked}))}/><span>I can perform mobile/on-site automotive work.</span></label><label className="mt-3 flex gap-3 text-sm text-muted"><input type="checkbox" checked={form.emergencyAvailable} onChange={e=>setForm(v=>({...v,emergencyAvailable:e.target.checked}))}/><span>I am interested in emergency/roadside jobs.</span></label></div>
  {error&&<div className="error mt-6">{error}</div>}<button className="mt-6 w-full rounded-2xl bg-blue px-5 py-4 text-sm font-semibold text-white disabled:opacity-50" disabled={busy}>{busy?'Submitting application…':'Submit technician application →'}</button>
  </section>
  <aside className="h-fit rounded-[2rem] border border-line bg-soft p-6 md:p-8 lg:sticky lg:top-24"><p className="text-xs font-semibold uppercase tracking-[.25em] text-blue">What happens next</p><div className="mt-7 space-y-7">{[['01','Review','Viso reviews your experience, specialties and service area.'],['02','Approval','Approved technicians receive an invitation to activate their Viso account.'],['03','Payouts','You complete secure Stripe Connect onboarding for payouts.'],['04','Jobs','Once approved and available, Viso can route eligible jobs to you.']].map(([n,t,x])=><div key={n} className="border-t border-line pt-5"><span className="text-xs font-bold text-blue">{n}</span><h3 className="mt-2 text-xl font-display">{t}</h3><p className="mt-2 text-sm leading-6 text-muted">{x}</p></div>)}</div><p className="mt-8 text-xs leading-5 text-muted">Viso uses your service capabilities and availability to determine which jobs you can receive. Location sharing is limited to active work/availability.</p></aside>
 </form></div></main>
}
function Section({title}){return <p className="mb-4 text-xs font-bold tracking-[.22em] text-blue">{title}</p>}
